### PR TITLE
slack bug fix

### PR DESCRIPTION
**Pull request by cassiovanhelden**

### CODE REVIEW

**Comment by LubosTomandl** [comment]
It seems like you are updating wrong Slack integration. The changes seem to be done to the one that is in the main category, Citrix branded. The one you are updating by this PR is the one from VIA_CITRIX_READY category. Please check @cassiovanhelden .

**Comment by cassiovanhelden** [comment]
Hi @LubosTomandl thanks for the reply. Can you point me to the correct steps to created this PR?

**Comment by LubosTomandl** [comment]
Just put the files not in the folder you did, but in the bundles/http/Citrix/Slack folder. There is probably the integration you wanted to update.

**Comment by cassiovanhelden** [comment]
@LubosTomandl Thanks, i'll close this one.

**Pull request closed without merging**
